# Generated by Django 4.0.6 on 2022-07-07 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=150, verbose_name='IP адрес')),
                ('port', models.IntegerField(verbose_name='Порт')),
                ('type_of_resource', models.CharField(choices=[('0', 'Windows'), ('1', 'Unix'), ('2', 'SQL')], default='0', max_length=2, verbose_name='Тип ресурса')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Владелец', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
