# Generated by Django 4.0.6 on 2022-07-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_host', '0002_alter_host_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='user',
            new_name='author',
        ),
    ]
